### PR TITLE
fix(): set state fixed in createLocation (#77)

### PR DESCRIPTION
**Pull request by daqst**
This is the proposed fix to #77, including tests.

### CODE REVIEW

**Comment by jthoms1** [comment]
I understand the fix for state, but not the reason for the routeDidChange event. Can you explain?

**Comment by daqst** [comment]
That's actually a mistake on my part.  I added that extra 'routeDidChange' event as a solution to another problem I encountered and didn't properly commit it to it's own branch.  For this PR, it should just be the one fix() commit.

**Comment by daqst** [comment]
Reverted the last change -- I'll add that as a separate feature PR as I originally intended to.

**Comment by jthoms1** [comment]
Thank you!

**Pull request merged**
